Welcome: Bem-vindo ao Consleak!

QuestionTitle: Sua pergunta
QuestionDescription: Por favor elabore
QuestionSubmit: Fazer pergunta!

QuestionPosted question: Sua pergunta "#{questionTitle question}" foi feita!

PostedQuestions: Perguntas feitas

PostedAnswers: Respostas dadas
PostAnAnswer: Dar uma resposta

AnswerText: Sua resposta

AnswerPosted: Muito obrigado!  Sua resposta foi dada!

BackToHomepage: Voltar à página inicial
